controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
send_email:
    path: /send-email
    controller: App\Controller\EmailController::sendEmail
    methods: ['POST']